# Generated by Django 4.2.11 on 2024-03-16 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discount', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalAsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('status', models.IntegerField(choices=[(1, 'Подтверждено'), (0, 'Отклонено'), (2, '')], default=2, verbose_name='Статус')),
                ('operation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вывод Asman',
                'verbose_name_plural': 'Выводы Asman',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('operation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операции')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payer', to=settings.AUTH_USER_MODEL, verbose_name='Плательщик')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операции')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discount.partner', verbose_name='Партнер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупка услуги',
                'verbose_name_plural': 'Покупки услуг',
            },
        ),
        migrations.CreateModel(
            name='BuyAsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Сумма')),
                ('img', models.ImageField(upload_to='buy_asman', verbose_name='Скриншот транзакции')),
                ('status', models.IntegerField(choices=[(1, 'Подтверждено'), (0, 'Отклонено'), (2, '')], default=2, verbose_name='Статус')),
                ('operation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупка Asman',
                'verbose_name_plural': 'Покупки Asman',
            },
        ),
    ]
