# Generated by Django 4.2.11 on 2024-03-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyasman',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
