# Generated by Django 4.2.11 on 2024-03-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_buyasman_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsmanRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='Курс')),
                ('standard', models.FloatField(verbose_name='Стандарт')),
                ('bronze', models.FloatField(verbose_name='Бронза')),
                ('silver', models.FloatField(verbose_name='Серебро')),
                ('gold', models.FloatField(verbose_name='Золото')),
            ],
            options={
                'verbose_name': 'Курс Asman и Статусы',
                'verbose_name_plural': 'Курс Asman и Статусы',
            },
        ),
        migrations.AlterModelOptions(
            name='buyasman',
            options={'verbose_name': 'Покупка Asman', 'verbose_name_plural': 'Asman (покупки)'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalasman',
            options={'verbose_name': 'Вывод Asman', 'verbose_name_plural': 'Asman (выводы)'},
        ),
    ]
