# Generated by Django 4.2.11 on 2024-03-20 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asmanrate',
            options={'verbose_name': 'Asman (курс и статус)', 'verbose_name_plural': 'Asman (курс и статус)'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'История платежей'},
        ),
        migrations.AddField(
            model_name='history',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discount.partner', verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='history',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user2', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.IntegerField(choices=[(1, 'Подтверждено'), (0, 'Отклонено'), (2, 'В обработке')], default=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='Плательщик'),
        ),
    ]
