# Generated by Django 4.2.11 on 2024-03-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_asmanrate_options_alter_history_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-operation_time',), 'verbose_name': 'Покупка услуги', 'verbose_name_plural': 'Покупки услуг'},
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.IntegerField(choices=[(1, 'Успешно'), (0, 'Ошибка'), (2, 'В обработке')], default=2, verbose_name='Статус'),
        ),
    ]
