# Generated by Django 4.2.11 on 2024-03-21 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_buyasman_options_alter_history_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='buy_asman',
        ),
        migrations.AddField(
            model_name='buyasman',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.history', verbose_name='Покупка Asman'),
        ),
    ]
