# Generated by Django 4.2.11 on 2024-03-21 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_remove_history_buy_asman_buyasman_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalasman',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyasman',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.history', verbose_name='Покупка Asman'),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.IntegerField(choices=[(1, 'Успешно'), (0, 'Отклонено'), (2, 'В обработке')], default=2, verbose_name='Статус'),
        ),
    ]
