# Generated by Django 4.2.11 on 2024-03-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_withdrawalasman_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalasman',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
