# Generated by Django 4.2.11 on 2024-03-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_withdrawalasman_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='asmanrate',
            name='address_asman',
            field=models.CharField(default='', max_length=255, verbose_name='Кошелёк Asman'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asmanrate',
            name='address_usdt',
            field=models.CharField(default='', max_length=255, verbose_name='Кошелёк USDT'),
            preserve_default=False,
        ),
    ]
