# Generated by Django 4.2.11 on 2024-03-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_asmanrate_address_asman_asmanrate_address_usdt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asmanrate',
            name='address_asman',
        ),
        migrations.RemoveField(
            model_name='asmanrate',
            name='address_usdt',
        ),
    ]
