# Generated by Django 4.2.11 on 2024-03-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_remove_asmanrate_address_asman_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsmanRate',
        ),
    ]
