# Generated by Django 4.2.11 on 2024-03-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_delete_asmanrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
