# Generated by Django 4.2.11 on 2024-03-16 17:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория партнера',
                'verbose_name_plural': 'Категории партнеров',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('qr', models.ImageField(blank=True, editable=False, null=True, upload_to='', verbose_name='QR')),
                ('img', models.ImageField(upload_to='partners', verbose_name='Изображение')),
                ('total_visits', models.IntegerField(verbose_name='Всего посещений')),
                ('cost_of_visit', models.FloatField(verbose_name='Стоимость посещения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='discount.partnercategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
