# Generated by Django 4.2.11 on 2024-03-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='total_visits',
            field=models.IntegerField(default=0, verbose_name='Всего посещений'),
        ),
    ]
