# Generated by Django 4.2.11 on 2024-03-16 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_alter_partnercategory_id_alter_partners_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
