# Generated by Django 4.2.11 on 2024-03-16 20:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_partners_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, если партнер должен считаться активным. Уберите эту отметку вместо удаления записи.', verbose_name='Активность')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('qr', models.ImageField(blank=True, editable=False, null=True, upload_to='', verbose_name='QR')),
                ('img', models.ImageField(upload_to='partners', verbose_name='Изображение')),
                ('total_visits', models.IntegerField(default=0, verbose_name='Всего посещений')),
                ('cost_of_visit', models.FloatField(verbose_name='Стоимость посещения')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='discount.partnercategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.DeleteModel(
            name='Partners',
        ),
    ]
