# Generated by Django 4.2.11 on 2024-03-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='buyasmanrequest',
            name='processed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
