# Generated by Django 4.2.11 on 2024-03-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_buyasmanrequest_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.FloatField(default=0, verbose_name='Количество монет'),
        ),
    ]
