# Generated by Django 4.2.11 on 2024-03-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_v_code_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='v_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код подтверждения'),
        ),
    ]
