# Generated by Django 4.2.11 on 2024-03-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='QR'),
        ),
    ]
