# Generated by Django 4.2.11 on 2024-03-16 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_partner_delete_partners'),
        ('accounts', '0004_alter_user_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyAsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('img', models.ImageField(upload_to='buy_asman', verbose_name='Скриншот транзакции')),
                ('status', models.IntegerField(choices=[(1, 'Подтвержденно'), (0, 'Отклоненно')], default=1, verbose_name='Статус')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупка Asman',
                'verbose_name_plural': 'Покупки Asman',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('info', models.CharField(max_length=255)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discount.partner', verbose_name='Партнер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payer', to=settings.AUTH_USER_MODEL, verbose_name='Плательщик')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalAsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('status', models.IntegerField(choices=[(1, 'Подтвержденно'), (0, 'Отклоненно')], default=1, verbose_name='Статус')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вывод Asman',
                'verbose_name_plural': 'Выводы Asman',
            },
        ),
        migrations.RemoveField(
            model_name='payments',
            name='user',
        ),
        migrations.DeleteModel(
            name='BuyAsmanRequest',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
