# Generated by Django 4.2.11 on 2024-03-15 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_photo_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyasmanrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='buyasmanrequest',
            name='processed',
            field=models.BooleanField(default=False, editable=False, verbose_name='Обработано'),
        ),
        migrations.AlterField(
            model_name='buyasmanrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
