# Generated by Django 4.2.11 on 2024-03-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_verified_alter_user_username_alter_user_v_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='v_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения'),
        ),
    ]
