# Generated by Django 4.2.11 on 2024-03-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_buyasman_payment_transfer_withdrawalasman_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Покупка услуги', 'verbose_name_plural': 'Покупки услуг'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='coins',
            new_name='balance',
        ),
        migrations.AlterField(
            model_name='buyasman',
            name='status',
            field=models.IntegerField(choices=[(1, 'Подтверждено'), (0, 'Отклонено'), (2, '')], default=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='withdrawalasman',
            name='status',
            field=models.IntegerField(choices=[(1, 'Подтверждено'), (0, 'Отклонено'), (2, '')], default=2, verbose_name='Статус'),
        ),
    ]
