# Generated by Django 4.2.11 on 2024-03-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_buyasmanrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyasmanrequest',
            name='screenshot',
            field=models.ImageField(upload_to='buy_asman', verbose_name='Скриншот транзакции'),
        ),
    ]
