# Generated by Django 4.2.11 on 2024-03-16 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_payment_options_rename_coins_user_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyasman',
            name='operation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='operation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='operation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='withdrawalasman',
            name='operation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операции'),
        ),
    ]
