# Generated by Django 4.2.11 on 2024-03-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_buyasman_operation_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyasman',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='withdrawalasman',
            name='processed',
        ),
    ]
