# Generated by Django 4.2.11 on 2024-03-15 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_buyasmanrequest_processed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='total',
            new_name='coins',
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
