# Generated by Django 4.2.11 on 2024-03-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_total_payments_coins_alter_payments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='info',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='coins',
            field=models.FloatField(verbose_name='Количество монет'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата операции'),
        ),
    ]
