# Generated by Django 4.2.11 on 2024-03-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_buyasman_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyasman',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма'),
        ),
    ]
