# Generated by Django 4.2.11 on 2024-03-16 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_buyasman_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='info',
        ),
    ]
