# Generated by Django 4.2.11 on 2024-03-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userstatuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatuses',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AddField(
            model_name='userstatuses',
            name='bronze',
            field=models.FloatField(default=0, verbose_name='Бронза'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstatuses',
            name='gold',
            field=models.FloatField(default=1, verbose_name='Золото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstatuses',
            name='silver',
            field=models.FloatField(default=1, verbose_name='Серебро'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstatuses',
            name='standard',
            field=models.FloatField(default=1, verbose_name='Стандарт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstatuses',
            name='vip',
            field=models.FloatField(default=1, verbose_name='VIP'),
            preserve_default=False,
        ),
    ]
