# Generated by Django 4.2.11 on 2024-03-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Стандарт', max_length=20, verbose_name='Статус'),
        ),
    ]
