# Generated by Django 4.2.11 on 2024-03-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyvideos',
            name='views',
        ),
    ]
