# Generated by Django 4.2.11 on 2024-03-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wallets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallets',
            old_name='address_asman',
            new_name='asman',
        ),
        migrations.RenameField(
            model_name='wallets',
            old_name='address_usdt',
            new_name='usdt',
        ),
    ]
