# Generated by Django 4.2.11 on 2024-03-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_asmanrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asmanrate',
            options={'verbose_name': 'Курс Asman', 'verbose_name_plural': 'Курс Asman'},
        ),
    ]
