# Generated by Django 4.2.11 on 2024-03-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_status_partner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('Стандарт', 'Стандарт'), ('Бронза', 'Бронза'), ('Серебро', 'Серебро'), ('Золото', 'Золото'), ('VIP', 'VIP')], default='Золото', max_length=50, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
