# Generated by Django 4.2.11 on 2024-03-22 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_status_remove_partner_status_partnercategory_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='name',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='partnercategory',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='discount.status', verbose_name='Статус'),
        ),
    ]
