# Generated by Django 4.2.11 on 2024-03-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_rename_name_status_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('id',)},
        ),
    ]
