# Generated by Django 4.2.11 on 2024-03-22 12:36

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_alter_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.status'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='cat',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='status', on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='discount.partnercategory', verbose_name='Категория'),
        ),
    ]
