# Generated by Django 4.2.11 on 2024-03-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0007_partner_status_alter_partner_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='discount',
            field=models.IntegerField(default=10, verbose_name='Скидка'),
        ),
    ]
