# Generated by Django 4.2.11 on 2024-03-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0008_partner_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='status',
        ),
        migrations.RemoveField(
            model_name='partnercategory',
            name='status',
        ),
        migrations.AddField(
            model_name='partner',
            name='discount_for_bronze',
            field=models.IntegerField(blank=True, default=1, verbose_name='Скидка (Bronze)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='discount_for_gold',
            field=models.IntegerField(blank=True, default=1, verbose_name='Скидка (Gold)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='discount_for_silver',
            field=models.IntegerField(blank=True, default=1, verbose_name='Скидка (Silver)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='discount_for_standard',
            field=models.IntegerField(blank=True, default=1, verbose_name='Скидка (Standard)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='discount_for_vip',
            field=models.IntegerField(blank=True, default=1, verbose_name='Скидка VIP'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
