# Generated by Django 4.2.11 on 2024-03-25 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0009_remove_partner_status_remove_partnercategory_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='discount.partnercategory', verbose_name='Категория'),
        ),
    ]
