# Generated by Django 4.2.11 on 2024-03-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0010_alter_partner_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='discount',
        ),
    ]
