# Generated by Django 4.2.11 on 2024-03-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0011_remove_partner_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='visits_for_bronze',
            field=models.IntegerField(blank=True, default=1, verbose_name='Посещения (Bronze)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='visits_for_gold',
            field=models.IntegerField(blank=True, default=1, verbose_name='Посещения (Gold)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='visits_for_silver',
            field=models.IntegerField(blank=True, default=1, verbose_name='Посещения (Silver)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='visits_for_vip',
            field=models.IntegerField(blank=True, default=1, verbose_name='Посещения (VIP)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='discount_for_vip',
            field=models.IntegerField(blank=True, verbose_name='Скидка (VIP)'),
        ),
    ]
