# Generated by Django 4.2.11 on 2024-03-25 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0013_partner_visits_for_standard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='discount_for_bronze',
            new_name='d_bronze',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='discount_for_gold',
            new_name='d_gold',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='discount_for_silver',
            new_name='d_silver',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='discount_for_standard',
            new_name='d_standard',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='discount_for_vip',
            new_name='d_vip',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='visits_for_bronze',
            new_name='v_bronze',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='visits_for_gold',
            new_name='v_gold',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='visits_for_silver',
            new_name='v_silver',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='visits_for_standard',
            new_name='v_standard',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='visits_for_vip',
            new_name='v_vip',
        ),
    ]
